from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0002_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maternalrecord',
            name='adolescent_early_disclosure_and_care_seeking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='adolescent_hiv_tested_and_received_results',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='adolescent_knows_early_anc_and_danger_signs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='adolescent_linked_to_pmtct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='adolescent_received_respectful_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='adolescent_received_srhr_counseling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='adolescent_reported_reduced_stigma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='adolescent_satisfied_with_anc_yfs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='adolescent_wait_time_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='complication_breech',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='complication_multiple_gestation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='complication_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='complication_placenta_previa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='completed_recommended_anc_visits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='facility_meets_yfs_standards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='first_ultrasound_gestation_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='harmful_gender_norms_reduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='high_risk_identified_through_ruaa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='male_partner_accompanied_anc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='male_partner_hiv_positive_linked_to_art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='male_partner_hiv_tested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='male_partner_knows_danger_signs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='male_partner_participated_counseling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='male_partner_supported_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='maternal_supplements_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='men_contribute_to_maternal_nutrition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='nutrition_counseling_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='partner_support_for_anc_and_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='private_confidential_consultation_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='provider_trained_in_yfs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='referral_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='referral_received_appropriate_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='referred_high_risk_pregnancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='severe_malnutrition_referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='ultrasound_before_24_weeks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='ultrasound_screened_high_risk',
            field=models.BooleanField(default=False),
        ),
    ]
