# Generated by Django 6.0.3 on 2026-03-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_maternalrecord_program_indicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternalrecord',
            name='family_planning_method',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('pills', 'Pills'), ('condom', 'Condom'), ('iud', 'IUD'), ('injectable', 'Injectable'), ('implant', 'Implant'), ('nfp', 'Natural Family Planning'), ('ligation', 'Ligation/BTL'), ('vasectomy', 'Vasectomy'), ('others', 'Others')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='maternalrecord',
            name='tetanus_toxoid_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('tt1', 'TT1'), ('tt2', 'TT2'), ('tt3', 'TT3'), ('tt4', 'TT4'), ('tt5', 'TT5/Completed')], default='none', max_length=5),
        ),
    ]
