from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0004_alter_maternalrecord_family_planning_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maternalrecord',
            name='benefit_detects_problems_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='benefit_encourages_anc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='benefit_enables_early_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='benefit_knows_due_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='benefit_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='benefit_reduces_transport_costs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='benefit_saves_travel_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='benefit_understands_baby_health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='client_explanations_clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='client_most_helpful_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='client_treated_with_respect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='client_visit_helped_understand_health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='first_ultrasound_current_pregnancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='previous_pregnancies_with_ultrasound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='previous_pregnancies_with_ultrasound_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='fp_discussed_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='fp_given_opportunity_to_ask_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='fp_methods_explained_clearly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='fp_understands_post_delivery_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='gbv_asked_about_safety',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='gbv_felt_safe_discussing_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='gbv_given_information_for_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='gbv_offered_help_or_referral',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='gbv_respectful_supportive_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='high_risk_pregnancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='nutrition_advised_iron_folic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='nutrition_discussed_foods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='nutrition_improved_diet_since_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='nutrition_understands_important_foods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='referral_reason_hiv_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='referral_reason_malpresentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='referral_reason_multiple_pregnancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='referral_reason_no_fetal_heartbeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='referral_reason_obstetric_complication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='referral_reason_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='referral_reason_severe_anemia_malnutrition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='sti_advised_on_prevention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='sti_asked_about_symptoms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='sti_discussed_infections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='sti_offered_testing_or_treatment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maternalrecord',
            name='ultrasound_service_helpful',
            field=models.BooleanField(default=False),
        ),
    ]
