# Generated by Django 6.0.3 on 2026-04-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_maternalrecord_client_feedback_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maternalrecord',
            name='adolescent_early_disclosure_and_care_seeking',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='adolescent_hiv_tested_and_received_results',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='adolescent_knows_early_anc_and_danger_signs',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='adolescent_linked_to_pmtct',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='adolescent_received_respectful_care',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='adolescent_received_srhr_counseling',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='adolescent_reported_reduced_stigma',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='adolescent_satisfied_with_anc_yfs',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='adolescent_wait_time_minutes',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='completed_recommended_anc_visits',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='facility_meets_yfs_standards',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='harmful_gender_norms_reduced',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='male_partner_accompanied_anc',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='male_partner_hiv_positive_linked_to_art',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='male_partner_hiv_tested',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='male_partner_knows_danger_signs',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='male_partner_participated_counseling',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='male_partner_supported_referral',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='men_contribute_to_maternal_nutrition',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='partner_support_for_anc_and_delivery',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='private_confidential_consultation_space',
        ),
        migrations.RemoveField(
            model_name='maternalrecord',
            name='provider_trained_in_yfs',
        ),
    ]
